backend:
  name: git-gateway
  branch: main  

media_folder: "images"       
public_folder: "/images"

collections:
  - name: "events"
    label: "Events"
    file: "events.json"   
    fields:
      - { label: "Events", name: "events", widget: "list", fields: [
          { label: "Title", name: "title", widget: "string" },
          { label: "Date", name: "date", widget: "datetime" },
          { label: "Duration", name: "duration", widget: "string" },
          { label: "Location", name: "location", widget: "string" },
          { label: "Description", name: "description", widget: "text" },
          { label: "Image", name: "image", widget: "image" },
          { label: "Tags", name: "tags", widget: "list" }
        ] }
